language: java
jdk:
  - oraclejdk8

os:
  - linux
  - win
  - osx
  
cache:
  directories:
    - $HOME/.m2
    - cargo
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    
before_install: cd core
script: mvn build

after_success:
  - mvn clean test jacoco:report coveralls:report
  
script: mvn clean compile

after_success:
  - mvn clean test verify jacoco:report coveralls:report
